name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-competitive-verifier-result-${{ matrix.index }}
          path: tests/pyres${{ matrix.index }}/competitive-verifier-result.json
          retention-days: ${{ inputs.retention-days }}

  test:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create docs local
        id: docs-local
        uses: ./
        with:
          local-verify-files-path: tests/verify-files.json
          local-result-path: tests/pyres*/competitive-verifier-result.json
          destination: ${{runner.temp}}/.competitive-verifier/_jekyll_local
          install: true
          cache-pip: true
          write-summary: false
      - name: Test local
        run: |
          [ $(wc -c < "$GITHUB_STEP_SUMMARY") = 0 ]
          rm $GITHUB_STEP_SUMMARY
          ls ${RUNNER_TEMP}/.competitive-verifier/_jekyll_local

      - name: Create docs local without write-summary input
        id: docs-local-without-write-summary
        uses: ./
        with:
          local-verify-files-path: tests/verify-files.json
          local-result-path: tests/pyres*/competitive-verifier-result.json
          destination: ${{runner.temp}}/.competitive-verifier/_jekyll_local
      - name: Test local without write-summary input
        run: |
          [ $(wc -c < "$GITHUB_STEP_SUMMARY") = 0 ]
          rm $GITHUB_STEP_SUMMARY
          ls ${RUNNER_TEMP}/.competitive-verifier/_jekyll_local
          
      - name: Create docs artifact
        id: docs-artifact
        uses: ./
        with:
          local-verify-files-path: tests/verify-files.json
          destination: ${{runner.temp}}/.competitive-verifier/_jekyll_artifact
          write-summary: true
      - name: Test artifact
        run: |
          [ $(wc -c < "$GITHUB_STEP_SUMMARY") > 0 ]
          rm $GITHUB_STEP_SUMMARY
          ls ${RUNNER_TEMP}/.competitive-verifier/_jekyll_artifact
